apiVersion: v1
kind: LimitRange
metadata:
  name: limits-range
spec:
  limits:
  - default:
      cpu: 1
      memory: 128Mi
    defaultRequest:
      cpu: 0.5
      memory: 64Mi
    max:
      cpu: 64
      memory: 4Gi
    min:
      cpu: 0.1
      memory: 32Mi